// Mocks generated by Mockito 5.4.2 from annotations
// in fast_trivia/test/features/quiz/data/repository/quiz_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fast_trivia/features/quiz/data/datasource/quiz_remote_data_source.dart'
    as _i2;
import 'package:fast_trivia/features/quiz/data/datasource/shared_preferences_data_source.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuizRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizRemoteDataSource extends _i1.Mock
    implements _i2.QuizRemoteDataSource {
  MockQuizRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getQuizes() => (super.noSuchMethod(
        Invocation.method(
          #getQuizes,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [SharedPreferencesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesDataSource extends _i1.Mock
    implements _i4.SharedPreferencesDataSource {
  MockSharedPreferencesDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveQuizesInHistory(String? quizes) => (super.noSuchMethod(
        Invocation.method(
          #saveQuizesInHistory,
          [quizes],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  String getQuizesHistory() => (super.noSuchMethod(
        Invocation.method(
          #getQuizesHistory,
          [],
        ),
        returnValue: '',
      ) as String);
}
